# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build .NET MAUI Android

on:
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches: 
      - main
      - dev

jobs:
  build:

    runs-on: macos-latest

    steps:
    
    - name: GitHub Checkout
      uses: actions/checkout@v4
      with:
        path: MauiGithubActions
      
    - name: GitHub Dependencies Checkout
      uses: actions/checkout@v4
      with:
        repository: JosueDM94/MauiGithubActions.Shared
        ref: main
        path: MauiGithubActions.Shared    

    - name: Install Keystore
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" > MauiGithubActions/"${{ secrets.KEYSTORE }}".asc
        gpg -d --passphrase "${{ secrets.KEYSTORE_PASSWORD_GPG }}" --batch MauiGithubActions/"${{ secrets.KEYSTORE }}".asc > MauiGithubActions/"${{ secrets.KEYSTORE }}"

    - name: Check path
      run: |
        ls
        ls MauiGithubActions
        ls MauiGithubActions.Shared
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
        
    - name: Install .NET MAUI Workload
      run: dotnet workload install maui
    
    - name: Update App Version
      uses: managedcode/MAUIAppVersion@v1.1.0
      with:    
        csproj: MauiGithubActions/MauiGithubActions.csproj
        version: ${{ github.run_number }}
        displayVersion: ${{ vars.APP_VERSION }}
        printFile: true
      
    - name: Publish Android App
      run: dotnet publish MauiGithubActions/MauiGithubActions.csproj -c Release -f net8.0-android -p:AndroidKeyStore=true -p:AndroidSigningKeyStore="${{ secrets.KEYSTORE }}" -p:AndroidSigningKeyAlias="${{ secrets.KEYSTORE_ALIAS }}" -p:AndroidSigningKeyPass="${{ secrets.KEYSTORE_PASSWORD }}" -p:AndroidSigningStorePass="${{ secrets.KEYSTORE_PASSWORD_ALIAS }}"

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifacts-android
        path: |
          ./**/publish/*.*
